config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get "signin", to: "users/sessions#new"
    post "signin", to: "users/sessions#create"
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
  end
  namespace :admin do
    root to: "users#index"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: Settings.post.title_size}
  validates :description, length: {maximum: Settings.post.title_size}
  validates :content, presence: true

  mount_uploader :picture, PictureUploader

  scope :feed_sort, ->{order created_at: :desc}
  scope :publish, ->{where is_published: true}
  scope :top_post, lambda {
    joins(:comments).select("COUNT(comments.id) AS comments_count, posts.*")
    .group("posts.id").order("comments_count DESC").limit Settings.post.limit_post
  }
  scope :search, ->(search){where "title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%"}
  scope :load_feed, ->(id, following_ids) do
    where "user_id IN (#{following_ids}) OR user_id = :user_id",
      following_ids: following_ids, user_id: id
  end

  def all_tags=names
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |post|
        csv << post.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :check, only: :index
  load_and_authorize_resource

  def index
    @posts = Post.order(:title).page(params[:page]).per_page 30
    respond_to do |format|
      format.html {@posts = Post.all}
      format.csv { send_data @posts.to_csv }
      format.xls { render text: @posts.to_csv(col_sep: "\t") }
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = t ".delete_success"
      redirect_to admin_posts_path
    else
      flash[:danger] = t ".failed_delete"
      redirect_to admin_posts_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :tag_all, only: :show

  def show
    @top_post = Post.top_post
  end

  def index
    if params[:q]
      @posts = Post.search(params[:q]).order(:title).page(params[:page]).per_page Settings.post.number_show
    else
      @posts = Post.all.publish
    end
  end

  def new
  end

  def create
    @post = current_user.posts.build post_params

    if @post.save
      flash[:success] = t ".post_success"
      redirect_to @post
    else
      @feed_items = []
      render :new
    end
  end

  def update
    if @post.update_attributes post_params
      flash[:success] = t ".update_success"
      redirect_to @post
    else
      flash.now[:danger] = t ".update_fail"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = t ".delete_success"
      redirect_to root_path
    else
      flash.now[:danger] = t ".delete_error"
      render request.referer
    end
  end

  private

  def post_params
    params.require(:post).permit :title, :description, :content, :picture,
      :is_published, :all_tags
  end

  def tag_all
    @tag_all = Tag.all
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, post %></td>
  <td>
    <%= post.user.name %>
  </td>
  <td>
    <% if can? :manage, post %>
      <%= link_to t(".delete"), admin_post_path(post), method: :delete, data: {confirm: t(".sure")}, class: "btn btn-danger button_text" %>
    <% end %>
  </td>
</tr>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <%= link_to t(".manageruser"), admin_users_path, class: "btn btn-primary" %>
    (<%= @posts.size %>) posts
    <p>
      Download:
      <%= link_to "CSV", admin_posts_path(format: "csv") %> |
      <%= link_to "Excel", admin_posts_path(format: "xls") %>
    </p>
    <div class="col-lg-10 col-md-offset-1">
      <div class="table-responsive">
        <table class="table user-list" id="my-users">
          <thead>
            <tr id="my-users">
              <th class="col-md-8"><%= t ".title"%></th>
              <th class="col-md-4"><%= t ".author" %></th>
              <th class="col-md-4"><%= t ".action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @posts %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
        <Cell><Data ss:Type="String">Author</Data></Cell>
      </Row>
    <% @posts.each do |post| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= post.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= post.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= post.content %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= post.user.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>