config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get "signin", to: "users/sessions#new"
    post "signin", to: "users/sessions#create"
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
  end
  namespace :admin do
    root to: "users#index"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :omniauthable,
    :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :avatar, AvatarUploader

  def feed
    following_ids = "SELECT followed_id FROM relationships
      WHERE follower_id = :user_id"
    Post.load_feed id, following_ids
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.name = auth.info.name
        user.email = auth.info.email
        user.password = "123123"
      end
    end

    def new_with_session params, session
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check, only: :index
  load_and_authorize_resource

  def index
    @users = User.order(:name).page(params[:page]).per_page 30
    respond_to do |format|
      format.html {@users = User.all}
      format.csv { send_data @users.to_csv }
      format.xls { render text: @users.to_csv(col_sep: "\t") }
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t ".delete_success"
      redirect_to admin_root_path
    else
      flash[:danger] = t ".delete_error"
      redirect_to fallback_location: admin_root_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:success] = t ".welcome"
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_resource only: [:show, :destroy]
  before_action :feed_all, only: :show

  def show
    @follow_user = current_user.active_relationships.build if user_signed_in?

    if current_user == @user
      @feed_items = current_user.posts.feed_sort.page(params[:page]).per_page Settings.post.number_show
    else
      @feed_items
    end
  end

  def index
    @users = User.order(:name).page(params[:page]).per_page Settings.user.user_show
  end

  def destroy
    if @user.destroy
      flash[:success] = t ".delete_success"
      redirect_to admin_root_path
    else
      flash[:danger] = t ".delete_error"
      redirect_back fallback_location: admin_root_path
    end
  end

  def following
    @user = User.find_by id: params[:id]
    @users = @user.following.paginate page: params[:page]
    render "show_follow"
  end

  def followers
    @user = User.find_by id: params[:id]
    @users = @user.followers.paginate page: params[:page]
    render "show_follow"
  end

  private

  def feed_all
    @feed_items = @user.posts.publish.feed_sort.page(params[:page]).per_page Settings.post.number_show
  end
end

app/views/admin/users/_user.html.erb
<tr>
  <td class="col-md-5">
    <%= link_to user.name, user %>
    <% if user.is_admin? %>
      (<%= t ".admin" %>)
    <% end %>
  </td>
  <td><%= user.email %></td>
  <td><%= user.posts.size %></td>
  <td>
    <% if current_user.is_admin? && current_user != user %>
      <%= link_to t(".delete"), user, method: :delete,
        data: {confirm: t(".sure")}, class: "btn btn-danger button_text" %>
    <% end %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <%= link_to t(".managerpost"), admin_posts_path, class: "btn btn-primary" %>
    (<%= @users.size %>) users
    <p>
      Download:
      <%= link_to "CSV", admin_users_path(format: "csv") %> |
      <%= link_to "Excel", admin_users_path(format: "xls") %>
    </p>
    <div class="col-lg-10 col-md-offset-1">
      <div class="main-box-body clearfix">
        <div class="table-responsive">
          <table class="table user-list" id="my-users">
            <thead>
              <tr id="my-users">
                <th class="col-md-4"><%= t ".user"%></th>
                <th class="col-md-4"><%= t ".email" %></th>
                <th class="col-md-4"><%= t ".posts" %></th>
                <th class="col-md-4"><%= t ".action" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render @users %>
              <div id="infinite-scrolling"></div>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Address</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
      </Row>
    <% @users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= user.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.address %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.phone %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>