config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get "signin", to: "users/sessions#new"
    post "signin", to: "users/sessions#create"
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
  end
  namespace :admin do
    root to: "users#index"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
  resources :users, only: [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="col-md-6 footer-left wow fadeInDown">
      <h4><%= t ".about_me" %></h4>
      <p><%= t ".text_about" %></p>
      <%= image_tag "BeThanhGiong.jpg", class: "img-responsive" %>
    </div>
    <div class="col-md-6 footer-middle wow fadeInDown">
      <h4><%= t ".sweet" %></h4>
        <p><i class="glyphicon glyphicon-print" aria-hidden="true"></i> <%= t ".name" %> : Be Thanh Giong</p>
        <p><i class="glyphicon glyphicon-phone" aria-hidden="true"></i> <%= t ".mobile" %> : 01688367495</p>
        <p><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i> <%= t ".email" %>: dkcbvn1995@egmail.com</p>
      <div class="mid-btm">
        <p><%= t ".sed" %></p>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="copyright wow fadeInDown">
  <div class="container">
    <p><%= t ".copyright" %><%= link_to t(".bebe"), "http://facebook.com/deumi.rct" %>
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header" id="ban">
  <div class="container">
    <div class="header_right wow fadeInLeft animated animated">
      <nav class="navbar navbar-default">
        <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
          <nav class="link-effect-7" id="link-effect-7">
            <ul class="nav navbar-nav">
              <li><%= link_to t(".home"), root_path %></li>
              <li><%= link_to t(".authors"), users_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to t(".post"), new_post_path %></li>
                <% if current_user.is_admin? %>
                  <li><%= link_to t(".admin"), admin_root_path %></li>
                <% end %>
                <li><%= link_to t(".account"), current_user %></li>
                <li><%= link_to t(".logout"), destroy_user_session_path,
                  method: :delete %></li>
              <% else %>
                <li><%= link_to t(".sign_up"), signup_path %></li>
                <li><%= link_to t(".sign_in"), signin_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </nav>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="header-bottom">
  <div class="container">
    <div class="logo wow fadeInDown">
      <h1><%= link_to t(".bebe_blog"), root_path, class: "nav-link" %></h1>
      <p><label class="of"></label><%= t ".style" %><label class="on"></label></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= t ".title" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,600,700" rel="stylesheet" type="text/css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>